name: metpy-cookbook
channels:
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - jupyter_server<2
  - jupyter-book
  - jupyterlab
  - matplotlib
  - metpy
  - numpy
  - pandas
  - scipy
  - siphon
  - xarray
  - pip:
      - sphinx-pythia-theme
